[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pythpredict = "J7TLVPzbd47RpiHV8BBPLQuixU53P5qijkrwkvN4u98W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = ".wallets/local-keypair.json"  

[scripts]
#test = "cargo test"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/pyth-integration.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/btc_prediction_market.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/devnet-claim.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/price-change-60sec.ts"

#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/advanced-market-dynamics.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-fixes.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/master-test.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/last.ts"

#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/btc_custom_rpc.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/setup.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
